version: '3.9'

services:

  php:
    build: ./php
    ports:
      - 8081:80
  db:
      image: postgres
      restart: always
      shm_size: 128mb
      environment:
        POSTGRES_PASSWORD: 12345

  pgadmin:
      image: dpage/pgadmin4
      restart: always
      ports:
        - 8080:80
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      depends_on:
        - db
